name: Execute automated checks
on:
  - push
jobs:
# https://github.com/golangci/golangci-lint-action#how-to-use
  lint:
    name: Lint go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.53.3
  test:
    name: Verify go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup golang
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: '1.17.0'
      - name: Print go version
        run: go version
      - name: Execute go tests 
        run: go test -v ./...
